# docker/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rwandapro-ims'
    static_configs:
      - targets: ['app:8080'] # Connect to Node.js app metrics
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187'] # Postgres Exporter

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121'] # Redis Exporter