version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rwandapro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rwandapro-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rwandapro"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    environment:
      REDIS_PASSWORD: redispass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rwandapro-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    build:
      context: .
      dockerfile: docker/prometheus/Dockerfile
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - rwandapro-net
    depends_on:
      - app
      - postgres
      - redis

  grafana:
    build:
      context: .
      dockerfile: docker/grafana/Dockerfile
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - rwandapro-net
    depends_on:
      - prometheus

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/rwandapro
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      RRA_API_KEY: ${RRA_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - rwandapro-net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  grafana_data:

networks:
  rwandapro-net:
    driver: bridge